Meta service grpc interfaces
soda-cdm/kahu pull request #22
Opened 2022-06-07 00:42 UTC by AmitRoushan

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

 **/kind enhancement**

**What this PR does / why we need it**:

The PR adds GRPC interfaces exposed by meta service for backup/restore.

**Which issue(s) this PR fixes**:

Fixes #21

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

/kind NOT-TESTED (auto generated code)

**Test Report**:

NA

**Special notes for your reviewer**:

2022-06-07 00:42 UTC, AmitRoushan commented
@sushanthakumar @joseph-v @PravinRanjan10

2022-06-07 04:52 UTC, joseph-v submitted a review, later dismissed
LGTM

2022-06-08 09:02 UTC, PravinRanjan10 requested changes

2022-06-10 02:01 UTC, AmitRoushan commented on providerframework/meta_service/proto/metaservice.proto
> +message BackResource {
Fixed typo error

2022-06-10 05:26 UTC, sodagitops commented
LGTM

2022-06-10 05:26 UTC, sodagitops approved these changes

2022-06-10 05:30 UTC, sushanthakumar approved these changes

2022-06-10 06:10 UTC, joseph-v approved these changes
LGTM

2022-06-12 16:18 UTC, sushanthakumar commented
@PravinRanjan10 pls check the updated changes and approve

2022-06-12 16:26 UTC, PravinRanjan10 approved these changes

2022-06-12 16:26 UTC, PravinRanjan10 commented
LGTM

2022-06-12 16:30 UTC, merged