Support controller manager framework
soda-cdm/kahu pull request #60
Opened 2022-06-28 22:54 UTC by AmitRoushan

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

/kind enhancement

**What this PR does / why we need it**:
The PR contribute to support generic controller manager framework for kahu controller manager
**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED
/kind TESTED
**Test Report**:

**Special notes for your reviewer**:

2022-06-29 04:21 UTC, AmitRoushan commented
@PravinRanjan10 @joseph-v @sushanthakumar 
PTAL

2022-06-30 05:28 UTC, sushanthakumar submitted a review, later dismissed
LGTM

2022-06-30 09:10 UTC, PravinRanjan10 requested changes

2022-06-30 09:35 UTC, sushanthakumar approved these changes
LGTM

2022-06-30 09:36 UTC, AmitRoushan commented on controllers/controller.go
> +func (ctrl *controller) Build() (Controller, error) {
The ```Build``` is part of builder pattern to get ```Controller``` interface. IMO, the method is valid and required to generate controller.
Note: Corrected duplicate ```handle``` and ```resyncHandler``` error check

2022-06-30 09:41 UTC, PravinRanjan10 approved these changes
LGTM

2022-06-30 09:42 UTC, merged