Build file update for image generation
soda-cdm/kahu pull request #95
Opened 2022-09-28 17:42 UTC by sushanthakumar

**What type of PR is this?**
kind enhancement

**What this PR does / why we need it**:
This PR update the build scripts to build all kahu components

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
kind TESTED

**Test Report**:

**Special notes for your reviewer**:

2022-10-08 03:36 UTC, joseph-v approved these changes
LGTM

2022-10-11 02:49 UTC, AmitRoushan requested changes

2022-10-11 02:49 UTC, AmitRoushan commented on build/lib/golang.sh
> +  volume-service
IMHO, binary names can be consistent.

2022-11-24 06:38 UTC, sushanthakumar commented
Outdated, closing the PR

2022-11-24 06:38 UTC, closed without merging